application: gnobble-cruise
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /hook
  script: hook.py

- url: /
  script: main.py  